
Arvore: main.o NoArvore.o 
	g++ main.o NoArvore.o -o Arvore

main.o: main.cpp
	g++ -c main.cpp

NoArvore.o: NoArvore.cpp NoArvore.hpp
	g++ -c NoArvore.cpp

clean:
	rm *.o Arvore

#no windows se usa o comando mingw32-make, e não so make